
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: fundoo_notess_development
  host: localhost
  port: 5432
  username: postgres
  password: Varun0709




production:
  primary: &primary_production
    <<: *default
    database: fundoo_notess_production
    username: fundoo_notess
    password: <%= ENV["FUNDOO_NOTESS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: fundoo_notess_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: fundoo_notess_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: fundoo_notess_production_cable
    migrations_paths: db/cable_migrate
test:
  <<: *default
  database: fundoo_notess_test
  host: localhost
  port: 5432
  username: postgres
  password: Varun0709

